import { AlertTriangle } from 'lucide-react';

export function Disclaimer() {
  return (
    <div className="fixed bottom-0 left-0 right-0 z-50 bg-muted/90 backdrop-blur-sm border-t py-2 px-4 text-center text-xs text-muted-foreground">
      <div className="flex items-center justify-center gap-2 max-w-4xl mx-auto">
        <AlertTriangle className="h-3 w-3 flex-shrink-0" />
        <div className="flex flex-col gap-1">
          <p>
            Agent McCarthy is an AI assistant. Responses are generated by
            artificial intelligence and may contain inaccuracies or
            hallucinations. Please verify important information independently.
          </p>
          <p className="text-[10px] opacity-80">
            Built with Next.js, OpenAI AgentSDK, and modern web technologies
          </p>
        </div>
      </div>
    </div>
  );
}
