import { AlertTriangle } from 'lucide-react';

export function Disclaimer() {
  return (
    <div className="fixed bottom-0 left-0 right-0 z-20 bg-muted/90 backdrop-blur-sm border-t py-1 sm:py-2 px-3 sm:px-4 text-center text-[9px] sm:text-[10px] md:text-xs text-muted-foreground pb-[max(0.25rem,env(safe-area-inset-bottom))] sm:pb-[max(0.5rem,env(safe-area-inset-bottom))]">
      <div className="flex items-center justify-center gap-1.5 sm:gap-2 max-w-4xl mx-auto">
        <AlertTriangle className="h-2.5 w-2.5 sm:h-3 sm:w-3 flex-shrink-0" />
        <div className="flex flex-col sm:gap-1">
          <p>
            Agent McCarthy is an AI assistant. Responses are generated by
            artificial intelligence and may contain inaccuracies or
            hallucinations. Please verify important information independently.
          </p>
          <p className="hidden sm:block text-[9px] sm:text-[10px] opacity-80">
            Built with Next.js, OpenAI AgentSDK, and modern web technologies
          </p>
        </div>
      </div>
    </div>
  );
}
